### ISSUE TITLE
'destructuring-bind' was obsolete in emacs 27, using `cl-destructuring-bind` instead and give the rolling-back compability

### ISSUE THREAD

**Issue by c0001** [tomoya/search-web.el#4]
Funciton `search-web` using the subroutine `destructuring-bind` of package `cl` was not loaded at init time, by follow the update of emacs 27 , package `cl-macs` as the default common lisp emulator library, hope for fixing this by wrapper with compability as the demo for:

``` elisp
(if (version< emacs-version "27")
    (require 'cl)
  (require 'cl-macs))
```
And it seems this package is inactive for four years, do you push out of it, or may I continuing  do with that?

**Comment by tomoya** [comment]
Hi, @c0001 
Thank you for your comment.
Actually, I no longer use this package.
If you want to do this package maintenance, I give you this package ownership. How about you?

**Comment by c0001** [comment]
Yes, that's what I wish to, `search-web.el` was the component of my emacs configuration, thanks a lot.

**Comment by tomoya** [comment]
Hi @c0001,
I am sorry too late reply.
I requested transfer this repository to you. Please check it. Thank you.
